### ISSUE TITLE
[git e github] Setup Linux e Windows

### ISSUE THREAD

**Issue by danielle8farias** [WoMakersCode/git-e-github#18]
Gostaria de saber se vocês estão aceitando contribuições de instalação para esse repositório. Minha ideia era trazer esses dois posts que já fiz no blog para cá. https://dev.to/womakerscode/tutorial-instalando-configurando-e-inicializando-o-git-no-windows-57cj e https://dev.to/womakerscode/instalando-configurando-e-inicializando-o-git-no-linux-2m96

**Comment by cyz** [comment]
Oi @danielle8farias aceitamos sim!
