### ISSUE TITLE
[ciclo-de-vida-basico] Inserir conteúdo na página trabalhando com branchs - PARTE2

### ISSUE THREAD

**Issue by Kamilahsantos** [WoMakersCode/git-e-github#3]
- [ ] Explicar o que é um merge

- [ ] Qual a utilidade de se fazer um merge

- [ ] Exemplo de um merge local

**Comment by esterfania** [comment]
Eii, boa noite! Posso puxar essa pra fazer!

**Comment by Kamilahsantos** [comment]
Obrigada @esterfania  :)

**Comment by esterfania** [comment]
Está finalizado e o pull request foi aberto! 😁
