### ISSUE TITLE
[Hands-on] Criar exercício para prática de comandos básicos - clonando um repositório

### ISSUE THREAD

**Issue by Kamilahsantos** [WoMakersCode/git-e-github#4]
- [ ] Como clonar um repositório (que você é a autora)

- [ ] Criando uma nova branch no repositório criado

- [ ] Adicionando arquivos, comitando e enviando para o seu repositório remoto

- [ ] Fazendo uma pull request

- [ ] Mergeando essa pull request via github

**Comment by Ploosh** [comment]
Oi Kamilah, tudo bem? Posso pegar essa issue?

**Comment by Kamilahsantos** [comment]
Oi @Ploosh tudo bem e vc?  Claro :)
