### ISSUE TITLE
[Hands-on] Criar exercício para prática de comandos básicos - adicionando sua remote origin

### ISSUE THREAD

**Issue by Kamilahsantos** [WoMakersCode/git-e-github#5]
- [ ] Adicionar a origem remota de um projeto local (comandos necessários para isso)

- [ ] Criando uma nova branch no repositório 

- [ ] Adicionando arquivos, comitando e enviando para o seu repositório remoto

- [ ] Fazendo uma pull request

- [ ] Mergeando essa pull request via github

**Comment by ALaurinne** [comment]
Olá @Kamilahsantos posso ajudar neste exercício?

**Comment by Kamilahsantos** [comment]
Oie, Claro pode sim @ALaurinne :)
